# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Create a File
      run: echo "hello from--9 ${{ matrix.runs-on }}" > file-${{ matrix.runs-on }}.txt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact-${{ matrix.runs-on }}
        path: file-${{ matrix.runs-on }}.txt
  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
        - name: Download All Artifacts
          id: artifact
          uses: actions/download-artifact@v4
          with:
            path: my-artifact
            pattern: my-artifact-*
            merge-multiple: true
        - name: Create report file
          if: steps.artifact.outcome == 'success'
          run: date +%s > test2.txt
    
        - name: commit and push the change file
          uses: stefanzweifel/git-auto-commit-action@v5
          id: auto-commit-action
          with:
            commit_message: Update the goldens
            commit_user_name: GitHub Actions
            commit_user_email: spreeloop-update-golens-bot@users.noreply.github.com
            file_pattern: '.'
            branch: ${{ github.head_ref }}
        - name: "Run if changes have been detected"
          if: steps.auto-commit-action.outputs.changes_detected == 'true'
          run: |
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/dispatches \
              -d '{"ref":"${{ github.head_ref }}"}'

        - name: "Run if no changes have been detected"
          if: steps.auto-commit-action.outputs.changes_detected == 'false' 
          run: |
            echo "No Changes!"
            exit 1
